### ISSUE TITLE
「検査陽性者の状況」の注釈の修正

### ISSUE THREAD

**Issue by hidamasaki** [gdg-fukushima/covid19#105]
## 改善詳細 / Details of Improvement
- 「検査陽性者の状況」に記載の注釈を修正したい。

## スクリーンショット / Screenshot

![福島県内の最新感染動向-福島県-新型コロナウイルス感染症対策サイト](https://user-images.githubusercontent.com/64124083/118628863-f931bb80-b807-11eb-842b-8bc3e4a592f4.png)

## 期待する見せ方・挙動 / Expected behavior
現状の「入院中」の数には自宅療養も含むため、注釈を以下のとおり修正。
　【修正前】（注）入院中には宿泊療養を含む
　【修正後】（注）入院中には宿泊療養および自宅療養を含む

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by shinbunbun** [comment]
@hidamasaki @donuzium ノーマルな日本語以外の言語も対応した方が宜しいでしょうか？

**Comment by donuzium** [comment]
@shinbunbun 可能な範囲でお願いします！
もし表記に困るようであれば、別IssueとしてもらってもOKですし、相談してもらってもOKです！

**Comment by shinbunbun** [comment]
@donuzium 了解しました！それでは、他言語対応は別Issueを立てようと思います！
