### ISSUE TITLE
英語版・やさしいにほんご版のi18n対応

### ISSUE THREAD

**Issue by donuzium** [gdg-fukushima/covid19#12]
## 概要 / Summary:
#10 のissueがクローズしたら、英語・やさしいにほんご版の多言語対応をしたいです。

他の言語もやりたいところではありますが、リソースが確保できなそうなのでまずは2言語版を目指せればと思います。

## 誰が使うか / For whom:
英語を使うユーザー, 初級程度の日本語が理解できるユーザー

## 何のために / For what:
多言語対応

## どのように実現するか / How:
ファイルをコピーして en.json, ja-basic.json ファイルを作成し、適宜翻訳を行う。
東京都のファイルで使えるところはそのまま使えるかなと思います。
https://github.com/tokyo-metropolitan-gov/covid19/tree/development/assets/locales

**Comment by koheitakahashi** [comment]
@donuzium 
こちら、やらせていただきたいです🙇‍♂️

**Comment by donuzium** [comment]
よろしくおねがいします！
言語を選択するためのセレクトボックスは、福島版にするときに一旦消してしまっているので、その部分に関しても復帰してもらえると嬉しいです！

**Comment by koheitakahashi** [comment]
ありがとうございます🙇‍♂️

> 言語を選択するためのセレクトボックスは、福島版にするときに一旦消してしまっているので、その部分に関しても復帰してもらえると嬉しいです！

承知しました💪
今日明日中には、レビューしていただくところまで持っていけると思います🙇‍♂️
