### ISSUE TITLE
県が発表するYouTubeのリンクをメニューへ追加したい

### ISSUE THREAD

**Issue by hagaji** [gdg-fukushima/covid19#29]
## 改善詳細 / Details of Improvement
- 県からの感染者発表速報がYouTubeで発表されるため、URLリンクをWebサイトへ追加したい。

## 期待する見せ方・挙動 / Expected behavior
- サイドメニュー「福島県【新型コロナ】関連情報一覧」の下に「YouTube: 新型コロナウイルス感染症関連【速報】」を追加
  - 外部リンクとし、下記のURLへリンクさせる
  - https://www.youtube.com/playlist?list=PLX7ij_QBlO5QlNpkBrYDwWEJ-LcBrUq4G

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by donuzium** [comment]
@hagaji WELCOME!!!!

**Comment by nozo-moto** [comment]
こちらやりますね
