### ISSUE TITLE
文言の修正とリンクの追加

### ISSUE THREAD

**Issue by donuzium** [gdg-fukushima/covid19#31]
## 概要 / Summary:
`development-pref`ブランチにて作業をお願いします。
[テストサイト修正案200409.pdf](https://github.com/gdg-fukushima/covid19/files/4457592/200409.pdf)

## 誰が使うか / For whom:
ユーザー

## 何のために / For what:
公式サイトとしてアップデートするため。

## どのように実現するか / How:
上記PDFを参考に、文言を修正する。
※「検査陽性者の状況」のセクションと、ロゴの差し替え、「検査実施数」のグラフの修正は別のIssue

**Comment by MizukiSonoko** [comment]
@donuzium 
やります！
