### ISSUE TITLE
検査実施数のグラフから、クルーズ船を抜く

### ISSUE THREAD

**Issue by donuzium** [gdg-fukushima/covid19#33]
## 概要 / Summary:
[テストサイト修正案200409.pdf](https://github.com/gdg-fukushima/covid19/files/4457592/200409.pdf)
のように、グラフを抜く。 #31 と別Issueなのは、グラフのロジックが入るため。

## 誰が使うか / For whom:
ユーザー

## 何のために / For what:
公式情報と一致させるため

## どのように実現するか / How:
data.jsonの形式は変更せずに、クルーズ船の分は0で表示する。

**Comment by MizukiSonoko** [comment]
@donuzium 
やります！
