### ISSUE TITLE
IEにてグラフが表示されない問題を修正する

### ISSUE THREAD

**Issue by donuzium** [gdg-fukushima/covid19#39]
## 起こっている問題 / The Problem
- IEにてグラフが表示されない。

## スクリーンショット / Screenshot

![image (2)](https://user-images.githubusercontent.com/1407941/79411440-ce11e280-7fdd-11ea-8262-49470f514a8d.png)

## 期待する見せ方・挙動 / Expected Behavior
- 他のブラウザのように、グラフを見えるようにする。

## 起こっている問題の再現手段 / Steps to Reproduce
1. Windows / IEでサイトを開く

## 動作環境・ブラウザ / Environment
- Windows
- Internet Explorer IE 11.0.180 (おそらく他のバージョンでも出ている報告あり)

**Comment by donuzium** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/issues?q=is%3Aissue+IE+is%3Aclosed

東京版見てると、こっちだけに起こってる問題っぽいですね。

**Comment by MizukiSonoko** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/issues/890
これとかですかね

**Comment by donuzium** [comment]
マージされた日付はMar 9なので、それは入ってると思うんですよね。

**Comment by donuzium** [comment]
エラーがわからないので、大きな差異と言えば、外部のdata.json読みに行くところだと思うんで、ちょっとそこをもとに戻した物を開発サイトにデプロイして試してみます。

**Comment by donuzium** [comment]
こういうエラーでした。
<img width="908" alt="Screen Shot 2020-04-16 at 12 48 44" src="https://user-images.githubusercontent.com/1407941/79412557-bc7e0a00-7fe0-11ea-880a-6555237650c0.png">
