### ISSUE TITLE
集計日の追記

### ISSUE THREAD

**Issue by hidamasaki** [gdg-fukushima/covid19#49]
## 改善詳細 / Details of Improvement
- 以下4つのグラフに、集計日を追記したい。
　1.陽性患者数　→　公表日
　2.検査件実施数　→　検査実施日
　3.新型コロナコールセンター相談件数　→　相談受付日
　4.帰国者・接触者相談センター相談件数　→　相談受付日

## スクリーンショット / Screenshot

![集計日の追記](https://user-images.githubusercontent.com/64124083/79947952-e1c1bb00-84ad-11ea-81d6-4ad93bcd9e37.png)

## 期待する見せ方・挙動 / Expected behavior
- 各グラフに集計日を追記し、いつ時点の数字なのか分かるようにしたい。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by MizukiSonoko** [comment]
@donuzium 
やります！

**Comment by donuzium** [comment]
@hidamasaki 
作成した画面についてちょっと相談させてください。

@MizukiSonoko さんに対応してもらって出てきた[画面](https://github.com/gdg-fukushima/covid19/pull/56#issue-407427849)で、本人も文言などに違和感があるということをPull Requestでフィードバックしてくれていますが、確かに「公表日」「相談受付日」という文言は、発表者・データ視点での表現になるので、ぱっとグラフを閲覧した人たちには分かりづらい印象を僕も感じました。
<img width="443" alt="Screen Shot 2020-04-24 at 0 04 47" src="https://user-images.githubusercontent.com/6281583/80012527-68a38180-8508-11ea-93e9-20fc4382d88e.png">

上記の作業を引き継いで、位置の問題かと考えて「相談受付日: 4/22 11人」というようにすると見やすくなるかと思い修正してみたところ、「相談件数」というタイトルと並んでしまい情報過多になったので、末尾につけてみましたが余計に分かりづらくなってしまいました。
<img width="443" alt="Screen Shot 2020-04-24 at 0 04 47" src="https://user-images.githubusercontent.com/1407941/80215749-ecc84700-8677-11ea-854b-fcf7248a9379.png">

右上エリアに情報が多いことで余計に混乱してしまう気もします。

**「△△の相談件数は、相談受付日○日に、✗件ありました」** というように見えてしまう事が原因だと考えます。

そのためタイトルがすでにあるので、「○日は✗件です」という情報を伝えることがわかりやすさにつながるのではないかと思い、シンプルに日付だけ入れたのがこの[画面](https://github.com/gdg-fukushima/covid19/pull/57)です。
<img width="443" alt="Screen Shot 2020-04-24 at 0 04 47" src="https://user-images.githubusercontent.com/1407941/80117819-9816c480-85c2-11ea-8f4d-79c97fa3b003.png">

日付だけにしたことで **「△△の相談件数は、○日に、✗件ありました」** というように情報が整理されるので、上記画面で表示するのはいかがでしょうか？

**Comment by hidamasaki** [comment]
@donuzium さん
@MizukiSonoko さん

御対応いただきありがとうございます。
私もこちらの表記がシンプルで素敵だと思います。
問題なければこちらを採用したいなーと思います。
![](https://user-images.githubusercontent.com/1407941/80117819-9816c480-85c2-11ea-8f4d-79c97fa3b003.png)

**Comment by donuzium** [comment]
@hidamasaki ありがとうございます！
では @MizukiSonoko さんのをベースに修正したバージョンを採用させていただきますね。
