### ISSUE TITLE
「陽性患者の属性」と「陽性患者数」の件数

### ISSUE THREAD

**Issue by hidamasaki** [gdg-fukushima/covid19#58]
## 起こっている問題 / The Problem
- 「陽性患者の属性」と「陽性患者数」の件数が更新されない。
-  4/24時点で新たな陽性患者の情報をアップロード（累計66名）したが、上記に反映されない。

## スクリーンショット / Screenshot

![陽性患者数等](https://user-images.githubusercontent.com/64124083/80217657-05862c00-867b-11ea-9ac7-b7084c5b1fd2.png)

## 期待する見せ方・挙動 / Expected Behavior
- 「陽性患者の属性」と「陽性患者数」の件数が正しく（「検査陽性者の状況」の「陽性者数（累積）」の数字と合致するようにしたい。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by donuzium** [comment]
おそらく原因は、ファイル更新日の前日まで時間軸（x軸）を作るという仕様にしたからだと思います。

hotfixとして扱いますので、すぐに対応します。

**Comment by hidamasaki** [comment]
@donuzium さん

ありがとうございます。
今後ですが、把握できる分は当日中に更新することとなります。

**Comment by donuzium** [comment]
何を最終日にするのかと言うのは難しいところですが、陽性患者数に関しては以下の~~優先順位~~最終日を決める優先順位で対応したいと思いますがいかがでしょうか @hidamasaki 

※いずれも陽性患者数・属性のみに関連します。
- データの最終日はファイル更新時間の**12時間前**とする。
    - このことで、午前中にアップがされれば前日までの分、午後にアップされれば当日の分として最終日を算出することになる。
- いずれも公表日が上記の条件より新しくなる事があれば（あまりケースは想定できないですが、未来の予定を入れる操作をしたようなケースに限られると思います）、その公表日を最終日とする。

上記の条件で、当面の運用は問題ないんじゃないかと思っています。
ただし明示的に「最終公表日がいつか？」という情報があることが正確だと思います。
この件は追ってIssue化していきましょう。

**Comment by donuzium** [comment]
優先順位 => 最終日を決めるための優先順位 についてですのでコメント修正しました。

**Comment by donuzium** [comment]
とりいそぎ、上記の修正を入れて書き出しをしてみました。
データの書き出しはデプロイと連動していないので、即時反映されています。

<img width="1118" alt="Screen Shot 2020-04-24 at 23 03 50" src="https://user-images.githubusercontent.com/1407941/80221226-f0f86280-867f-11ea-997b-48542d341a59.png">

**Comment by hidamasaki** [comment]
@donuzium さん

迅速な御対応、ありがとうございます！
最終日の決め方については、御提案のとおりで問題ないものと思っております。
最終公表日の明示については追って議論させてください。

**Comment by donuzium** [comment]
では残りの課題を #59 に引き継ぎ、解決したコードを取り込んだため、クローズ致します。
