### ISSUE TITLE
「検査陽性者の状況」に注記を追加したい

### ISSUE THREAD

**Issue by hidamasaki** [gdg-fukushima/covid19#66]
## 改善詳細 / Details of Improvement
- 「検査陽性者の状況」の入院者について、宿泊療養者を含んだ数であるため、誤解の無いよう注釈を追記したい。

## スクリーンショット / Screenshot

![陽性患者の状況](https://user-images.githubusercontent.com/64124083/80667346-e7d12080-8ad9-11ea-8d99-8e7a5b2b6289.png)

## 期待する見せ方・挙動 / Expected behavior
- 「検査陽性者の状況」に以下の注記を追加したい。
　　（注）入院中には宿泊療養を含む

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by donuzium** [comment]
@hidamasaki 文言の追加の更新のため、私の方で確認して本番環境に反映しています！

ご確認ください〜

**Comment by hidamasaki** [comment]
@donuzium さん

修正反映、確認いたしました。
御対応いただきありがとうございました！

**Comment by donuzium** [comment]
ありがとうございます！
ちなみに作業したのは僕ではなくて新しくコミットしてくれた @toricoco さんです。

**Comment by hidamasaki** [comment]
@toricoco さん
作業いただきありがとうございました！
引き続きどうぞよろしくお願いいたします。

**Comment by toricoco** [comment]
@hidamasaki こちらこそどうぞよろしくお願いいたします！
