### ISSUE TITLE
「新型コロナウイルス感染症が心配なときに」の修正

### ISSUE THREAD

**Issue by hidamasaki** [gdg-fukushima/covid19#75]
## 改善詳細 / Details of Improvement
- 厚生労働省からの通知により、相談・受診の目安が変更となったことに伴い、「新型コロナウイルス感染症が心配なときに」に掲載しているフロー図を修正したい。

## スクリーンショット / Screenshot

![sinpainatokini](https://user-images.githubusercontent.com/64124083/81795154-c4c95680-9546-11ea-85af-823a0a981d83.png)

## 期待する見せ方・挙動 / Expected behavior
- 以下のイメージのとおり修正をしたい。
![修正案 (1)](https://user-images.githubusercontent.com/64124083/81797158-605bc680-9549-11ea-931f-7e3de807b568.png)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by donuzium** [comment]
@hidamasaki 新しいイメージを確認しました。スマートフォン版だと若干表示が異なるので、レイアウトに関しては少し調整が入るかとは思います。

画面下部の「新型コロナ受診相談窓口 による相談結果」に関しては、削除するということでいいでしょうか？

**Comment by donuzium** [comment]
PC画面の方から着手しています。

**Comment by donuzium** [comment]
@hidamasaki https://github.com/gdg-fukushima/covid19/pull/77#issuecomment-628102435
こちらでPC画面の修正点などが確認できます。
修正点なども書いてあるので（プルリクエストといいます）、ご確認いただけますか？

**Comment by hidamasaki** [comment]
@donuzium さん
プルリクエストを確認しました。早々に御対応いただきありがとうございます。
細かいところではありますが、以下の通り修正いただけますでしょうか。
また、画面下部の「新型コロナ受診相談窓口 による相談結果」はそのままイキでお願いいたします。

![修正案2](https://user-images.githubusercontent.com/64124083/81877729-d8190800-95c0-11ea-810e-7391c79921f6.png)

**Comment by donuzium** [comment]
@hidamasaki 
ご確認ありがとうございます！
修正版をアップしておりますので、こちらをご確認くださいませ。
https://github.com/gdg-fukushima/covid19/pull/77#issuecomment-628656823

**Comment by hidamasaki** [comment]
@donuzium さん

修正対応、ありがとうございます。

修正反映、確認いたしました。バッチリでございます！
こちらでアップいただければ幸いです。

**Comment by donuzium** [comment]
@hidamasaki ご連絡が遅くなってしまいましたが、金曜日の夜にこのissueと #78 について対応したものを本番環境へデプロイ致しました。
