### ISSUE TITLE
棒グラフの表示について

### ISSUE THREAD

**Issue by hidamasaki** [gdg-fukushima/covid19#82]
## 改善詳細 / Details of Improvement
- 棒グラフで表示されている以下の4項目について、現状、開始当初から現在までの推移が表示されているが、デフォルトの表示を直近2か月分とし、スクロールバーによりそれ以前の推移を見られるようにしたい。

## スクリーンショット / Screenshot

◆福島県版サイトの棒グラフ表示
![福島県内の最新感染動向_福島県_新型コロナウイルス感染症対策サイト](https://user-images.githubusercontent.com/64124083/84966206-e3c19680-b14b-11ea-824f-99695e257bca.png)
↓
（参考）東京都版サイトの棒グラフ表示
![都内の最新感染動向_東京都_新型コロナウイルス感染症対策サイト](https://user-images.githubusercontent.com/64124083/84966260-0784dc80-b14c-11ea-9cb3-39f414881fd4.png)

## 期待する見せ方・挙動 / Expected behavior
- 東京都版コロナ対策サイトのように表示させたい。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by donuzium** [comment]
作業を開始しました。

**Comment by donuzium** [comment]
@hidamasaki 大変おまたせしました。
https://83-dot-fukushima-covid19.appspot.com
こちらの環境にアップしています。まだIEなどのブラウザでは試していないので、こちらでも確認して見ようと思います。

**Comment by hidamasaki** [comment]
@donuzium 
修正内容、確認いたしました。
非常に見やすくなったと思います。
本番環境へ反映いただければ幸いです。
お忙しい中、御対応いただき感謝申し上げます(><)

**Comment by donuzium** [comment]
@hidamasaki 
ご確認ありがとうございました。
Y軸がちょっと整合していない問題を発見したので、その点のみ修正して反映致します。

**Comment by donuzium** [comment]
@hidamasaki Y軸のグラフが修正されていることを確認しましたので、本番環境へ配信いたしました！

**Comment by hidamasaki** [comment]
@donuzium 本番環境への反映、確認いたしました。
お忙しいところ御対応いただきありがとうございました！
御迷惑をお掛けいたしますが、引き続きよろしくお願いいたします。

**Comment by hidamasaki** [comment]
@donuzium 
closedのissuesに申し訳ないのですが、
IEで閲覧した際に、棒グラフの上にカーソンをオンしても、日付と件数が表示されないようです。
お忙しいとは思いますが、ご確認いただけますと幸いです。
