### ISSUE TITLE
IEでのマウスオーバー時に日付と件数が表示されない問題の修正

### ISSUE THREAD

**Issue by donuzium** [gdg-fukushima/covid19#85]
IEでグラフ上にマウスオーバーしたときに、他のブラウザでは日付と件数が表示されているが、IEでは表示されない問題を解決したい。

以下Issueのコメント

@donuzium 
closedのissuesに申し訳ないのですが、
IEで閲覧した際に、棒グラフの上にカーソンをオンしても、日付と件数が表示されないようです。
お忙しいとは思いますが、ご確認いただけますと幸いです。

_Originally posted by @hidamasaki in https://github.com/gdg-fukushima/covid19/issues/82#issuecomment-664067799_

**Comment by toricoco** [comment]
自分の環境で確認したところ、マウスオーバーで正常に表示されるようです。
Windows10 (1909)
IE11 (11.959.18362.0)
![ie11](https://user-images.githubusercontent.com/1311699/88634016-c5f33400-d0f0-11ea-93ef-ed633d00aa79.png)

@hidamasaki
エラーとなる環境について教えていただいても良かったでしょうか。

**Comment by hidamasaki** [comment]
@toricoco 
御確認いただきありがとうございます。
正常に表示されていますね；
私が確認していたのが仮想端末という職場の特殊な環境だったからかもしれません。
大変失礼いたしました・・。
