### ISSUE TITLE
陽性患者の集計日について

### ISSUE THREAD

**Issue by hidamasaki** [gdg-fukushima/covid19#89]
## 改善詳細 / Details of Improvement
- 【陽性患者の属性】及び【陽性患者数】の集計日を、更新日でなく陽性判明日としたい。

## スクリーンショット / Screenshot
![福島県内の最新感染動向-福島県-新型コロナウイルス感染症対策サイト](https://user-images.githubusercontent.com/64124083/93736394-20a19b80-fc1b-11ea-87c5-7d3151bcba3a.png)

## 期待する見せ方・挙動 / Expected behavior
これまでは更新日=陽性判明日であったが、9/19判明分より翌日公表としているため、【陽性患者の属性】及び【陽性患者数】の集計日を、更新日でなく陽性判明日（csvデータ　～patients.csvの公表年月日）としたい。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by donuzium** [comment]
hidaさんと電話で内容について確認。
- 以前の変更で公表日は最終年月日を X 軸の最終日としてしまうと感染確認患者数が0人だった場合にグラフに表示されないという問題があり、ファイルの更新日を最終日としてグラフを描画する方法に変更していました。
- 現在は前日までの集計を公表年月日として追加している状態なので、ファイル更新日の日付から-1日をした日付までのデータを作成する必要があるということです。
- 表示上の変更は今回必要ないということが確認できています。あくまでデータを書き出すところのプログラムを修正するという形になります。

**Comment by hidamasaki** [comment]
@donuzium 
御認識に相違ありません。
お忙しいところ大変恐縮ですが、
御対応の程、よろしくお願いいたします。

**Comment by donuzium** [comment]
@hidamasaki 本日、データ更新のプログラムを更新しました。対応が遅くなってしまい、大変失礼いたしました。

https://fukushima-covid19.web.app/

**Comment by hidamasaki** [comment]
@donuzium 
こちらも御連絡が遅くなり失礼しました。
更新反映を確認いたしました！
お忙しい中御対応いただき感謝申し上げます・・。
