### ISSUE TITLE
「新型コロナウイルス感染症が心配なときに」の更新

### ISSUE THREAD

**Issue by hidamasaki** [gdg-fukushima/covid19#90]
## 改善詳細 / Details of Improvement
　・相談フローの変更（まずはかかりつけ医などの身近な医療機関に相談）
　・相談窓口の名称変更（「帰国者・接触者相談センター」→「受診・相談センター」）
に伴い、
　①メインページに記載の相談センターの名称修正
　②「新型コロナウイルス感染症が心配なときに」の更新
を行いたい。

## スクリーンショット / Screenshot

　①メインページに記載の相談センターの名称修正
![福島県内の最新感染動向-福島県-新型コロナウイルス感染症対策サイト](https://user-images.githubusercontent.com/64124083/99204003-9da25900-27f7-11eb-97c4-a2e2f2830b0d.png)
　②「新型コロナウイルス感染症が心配なときに」の更新
![image](https://user-images.githubusercontent.com/64124083/99203851-35537780-27f7-11eb-8f7e-c56e4df4a477.png)

## 期待する見せ方・挙動 / Expected behavior
①メインページに記載の相談センターの名称修正
　「帰国者・接触者相談センター」を「受診・相談センター」に修正。

②「新型コロナウイルス感染症が心配なときに」の更新
　以下のExcelのとおりフロー図を更新したい。

[11.16対策サイト更新(広報課).xlsx](https://github.com/gdg-fukushima/covid19/files/5543601/11.16.xlsx)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by hitokuno** [comment]
「新型コロナウイルス感染症が心配なときに」の更新は下記で如何でしょうか?  添付されていた図では文字が多かったので簡略化してみました。
![Issue90_PC](https://user-images.githubusercontent.com/6281440/104850287-926fc480-5931-11eb-8b31-5bcd6b51fddf.jpg)

**Comment by hidamasaki** [comment]
@hitokuno 
ご対応いただきありがとうございます。
細かい点ではありますが、添付の通り修正いただけますでしょうか。
　※手書きのため、見にくいところがありましたら申し訳ありません・・。

![修正要望210118](https://user-images.githubusercontent.com/64124083/104860532-73902300-596f-11eb-97f3-32ed35826a77.JPG)
